name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v18-
      - name: Install Dependencies
        run: npm install
      - name: Node Tests
        run: npm run test